### ISSUE TITLE
Tipset cached frequently triggers "out of order"

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel-visor#321]
Running `v0.4.0-rc1` in staging frequently triggers the "tipset out of order" error. Data is still being inserted into the DB despite the error. It may be conincidental, but eventually ingestion does halt.

Attached logs with surrounding context: https://gist.github.com/placer14/3e240b801377b19bd4f4e43402f7d054

Visor config:
```yaml
watch:
  enabled: true
  confidence: 0
  tasks:
    - blocks
    - messages
    - chainEconomics
    - actorStatesRaw
```
